AddMinimapAtlas("map_icons/minimap_coffeebush.xml")
AddMinimapAtlas("map_icons/minimap_bittersweetbush.xml")
AddMinimapAtlas("map_icons/minimap_mintybush.xml")
AddMinimapAtlas("map_icons/minimap_pond_open.xml")
AddMinimapAtlas("map_icons/minimap_rock_slimey.xml")