GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Wait... does this mean I can make coffee?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "So... what do I have to do with this?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "And now what?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "Can I... eat this?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Finally... a fresh cup of coffee!"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBUSH = "I am no good at identifying poisonous berries"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BITTERSWEETBUSH = "Should I even plant this?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES = "It does not seem safe to eat"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES_COOKIED = "Even cooked it seems like a bad idea to eat this"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PERMA_GRASSGEKKO = GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSGEKKO
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.REINGOAT = "Rudolph?!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.LEIF_SNOW = "It looks like a Christmas tree..."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.RABBIT_SNOW = "It's a rabbit"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PERMA_WALRUS_CAMP = "Something tells me this is going to be bad."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.POND_OPEN = "Ice fishing!"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGMAN_BLUE = "It's a chillpig."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGMAN_GRAY = "They look angry."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGKING_GRAY = "Why does he sleep so much?"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGKING_BLUE = "King of the chillpigs?"

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MIMI = "Mimi?"
