
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "I can't believe I can actually have coffee here!"

--STRINGS.CHARACTERS.WILSON.DESCRIBE.COFFEE = "Scientist's best friend on lone nights in the lab."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEE = "Black like charcoal. Well burnt."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEE = "Coffee makes Wolfgang want go buttkicking for goodness!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEE = "Dark like this world. How fitting."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEE = "I don't need it to stay awake, yet the flavour..."

STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEE = "AN UNEXPECTED FUEL TYPE. DOES ITS WORK THOUGH."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEE = "It keeps the Valkyrie fighting!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEE = "Mum would tell Dad not to drink it late."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEE = "Like back in Cisco."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEE = "If only I had buttered scones too..."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "Wait... Coffeebushes? Here?"

--STRINGS.CHARACTERS.WILSON.DESCRIBE.COFFEEBUSH = "Do you know you're in the incorrect biome?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBUSH = "Can we get through this awkward phase and cut to burning your beans please?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBUSH = "Yuck, those berries! Too bitter when raw!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBUSH = "One could brew coffee with those berries, black as the darkest dungeon."

STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBUSH = "EXPERIMENTAL FUEL PLANT."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBUSH = "Freyr has blessed you, coffeebush."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBUSH = "Smells like Dad's coffee!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBUSH = "As close to a café I can get here."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBUSH = "This feller smells faintly of coffee."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBUSH = "Some specimen of the Coffea genus evidently adapted to local climate conditions."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "The beginnings of my own plantation."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.DUG_COFFEEBUSH = "Ready to start a properly-scientific coffee plantation."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_COFFEEBUSH = "To get to coffeebean-burning, I need to plant this first."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_COFFEEBUSH = "I plant, you give coffee."

STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_COFFEEBUSH = "Should we cultivate this, Abigail?"

STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_COFFEEBUSH = "COFFEE-BASED FUEL BLUEPRINT."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_COFFEEBUSH = "I should plant it to please Freyr."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_COFFEEBUSH = "Let's go gardening!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_COFFEEBUSH = "The measures I have to take for a cup..."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_COFFEEBUSH = "We can grow our own coffee with this feller here."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_COFFEEBUSH = "Let's see if the climate is appropriate."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "Now, the real question: how to turn those into coffee?"
  
--STRINGS.CHARACTERS.WILSON.DESCRIBE.COFFEEBEANS = "I'd always buy it prepared for brewing. This needs more tests."
  
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBEANS = "Meet my lucky lighter and prepare to be burnt!"
  
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBEANS = "Yuck. Wolfgang needs do more work."
  
STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBEANS = "I shall sacrifice these to sate my thirst for liquid darkness."
  
STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBEANS = "FLESHLINGS COMPLICATE EVERYTHING."
  
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBEANS = "Well-formed indehiscent drupes."
  
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBEANS = "Not ready for coffee and scones yet, Luce..."
  
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBEANS = "I should scry what Freyr wishes me to do with those beans."
  
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBEANS = "I don't think Dad drank those beans like that."
  
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBEANS = "Ha! Barista, where are you when I need you?!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "I suppose they are edible now. But... My coffee..."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.COFFEEBEANS_COOKED = "An avant-garde way of using the beans, fitting for a pioneer of science like me!"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBEANS_COOKED = "You burned so nicely. I admire you, little beans."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBEANS_COOKED = "Still bitter, but good."

STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBEANS_COOKED = "You're dead. It's official."

STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBEANS_COOKED = "THE INFERIOR FUEL VARIANT."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBEANS_COOKED = "Looks edible enough, eh?"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBEANS_COOKED = "Their sacrifice will not be forgotten."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBEANS_COOKED = "I'm not an African civet to possibly eat it in this state."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBEANS_COOKED = "A bit like what Mum used to brew coffee for Dad."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBEANS_COOKED = "I begin to dislike coffee for the handiwork involved."



STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "Finally... A fresh cup of coffee, the best sort!"
    
--STRINGS.CHARACTERS.WILSON.DESCRIBE.COFFEE = "I brewed it with SCIENCE!"
    
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEE = "The aroma: smoky. Hot."
    
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEE = "Wolfgang made coffee!"
    
STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEE = "I like the hue. Like funeral attires."
    
STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEE = "THIS FUEL IS SURPRISING EFFICIENT."
    
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEE = "It's dark like the depths of Niflheim itself."
    
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEE = "Just like Dad!"
    
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEE = "Insomnia never bothered me anyway."
    
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEE = "It has a woody scent. I like my coffee best this way."
    
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEE = "At long last! Not The Ritz, but will do for now." 


STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBUSH = "Looks poisonous if I'm any judge."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.BITTERSWEETBUSH = "A new plant species? Here comes your discoverer!"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BITTERSWEETBUSH = "...Why do I feel like burning you would be enjoyable AND smart?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BITTERSWEETBUSH = "A strange bush!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.BITTERSWEETBUSH = "One fruit away from nothingness. How appealing."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BITTERSWEETBUSH = "Worrisomely akin to Actaea pachypoda. I think I will pass this time; I don't want a cardiopulmonary arrest."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BITTERSWEETBUSH = "Manfredi and Johnson ate similar stuff one day after choppin'. They would never be the same, poor sops."

STRINGS.CHARACTERS.WX78.DESCRIBE.BITTERSWEETBUSH = "ANOTHER USELESS CARBON-BASED LIFE FORM."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BITTERSWEETBUSH = "Loki's trickery embodied, I wager."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BITTERSWEETBUSH = "Mum said not to eat unknown plants."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BITTERSWEETBUSH = "Adding your own mark upon this place, Charlie?"



STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BITTERSWEETBUSH = "Dug up, looks safe... for now."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.DUG_BITTERSWEETBUSH = "A prepared experimental farmplot sounds like a good idea."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_BITTERSWEETBUSH = "Fuel the stakes!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_BITTERSWEETBUSH = "Is bad bush."

STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_BITTERSWEETBUSH = "My portable demise device."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_BITTERSWEETBUSH = "That's one thing I'd rather get the forest rid of."

STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_BITTERSWEETBUSH = "HA. NOT SO SMART WITHOUT YOUR CIRCUITS ANYMORE."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_BITTERSWEETBUSH = "Temporarily unthreatening, but still toxic."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_BITTERSWEETBUSH = "I'm not sure if we should plant it back..."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_BITTERSWEETBUSH = "A vile foe could make poison with this."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_BITTERSWEETBUSH = "You create it, I spread the disease."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES = "Do those appear toxic or is it just me?"

--STRINGS.CHARACTERS.WILSON.DESCRIBE.BITTERSWEETBERRIES = "Are those poisonous? ...Best to get to practical tests."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BITTERSWEETBERRIES = "Fire will purify you... Hopefully."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BITTERSWEETBERRIES = "Wolfgang likes red berries more!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.BITTERSWEETBERRIES = "They have an acrid smell."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BITTERSWEETBERRIES = "We had better not eat those, Luce."

STRINGS.CHARACTERS.WX78.DESCRIBE.BITTERSWEETBERRIES = "I WANT TO WATCH THE MEATBAGS SQUIRM IN AGONY AFTER EATING THOSE."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BITTERSWEETBERRIES = "They smell like death, funeral pyres and treachery."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BITTERSWEETBERRIES = "They virtually brim with toxin."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BITTERSWEETBERRIES = "I have a bad feeling about this."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BITTERSWEETBERRIES = "I think I'm playing with fire."



STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES_COOKED = "They don't look half that bad as raw... That's still worlds away from \"tasty\"."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Let's see how toxic this variant is."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Fire purifies everything... Or does it?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Should Wolfgang eat this?"

STRINGS.CHARACTERS.WENDY.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Delicately-braised agony."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Cookin' hardly helped."

STRINGS.CHARACTERS.WX78.DESCRIBE.BITTERSWEETBERRIES_COOKED = "POISON AND THERMIC PROCESSING. I ADMIRE MY CREATIVITY."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BITTERSWEETBERRIES_COOKED = "He may survive this, but what about me?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Heat treating reduces the toxicity of the berries to an extent."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BITTERSWEETBERRIES_COOKED = "They may return unscathed from Muspelheim, no less, but they are still untrustworthy in my eyes."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BITTERSWEETBERRIES_COOKED = "Could have been worse."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.MINTYBUSH = "It gives off a fresh aroma."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.MINTYBUSH = "I could develop a new formula of toothpaste with this plant."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.MINTYBUSH = "Your berries seem too cold for my tastes."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MINTYBUSH = "Blue bush smells funny."

STRINGS.CHARACTERS.WENDY.DESCRIBE.MINTYBUSH = "This plant smells surprisingly like toothpaste."

STRINGS.CHARACTERS.WX78.DESCRIBE.MINTYBUSH = "YET ANOTHER USELESS CARBON-BASED LIFE FORM."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.MINTYBUSH = "I've never seen that bush before. The smell is vaguely familiar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MINTYBUSH = "Can it be? The ultimate solution to dental problems in this land?"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.MINTYBUSH = "It smells just like toothpaste!"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MINTYBUSH = "It carries the breath of the frost giants themselves."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MINTYBUSH = "It's been a long time since my last mint."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_MINTYBUSH = "I can use it as an air freshener anywhere now."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.DUG_MINTYBUSH = "It's ready to be planted in a better place where SCIENCE reigns!"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_MINTYBUSH = "Not so cool now, are you?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_MINTYBUSH = "My own toothpaste bush."

STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_MINTYBUSH = "I suppose I can find a better place for it now."

STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_MINTYBUSH = "NOT SO COOL NOW, PUNY FLESHLING."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_MINTYBUSH = "Where should we replant it, Lucy?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_MINTYBUSH = "The foundations of my own plantation of Mentha piperita."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_MINTYBUSH = "We can plant it somewhere now."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_MINTYBUSH = "I can pay homage to Freyr by planting this somewhere."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_MINTYBUSH = "A promise of gardening. Ugh."



STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES = ""

--STRINGS.CHARACTERS.WILSON.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WENDY.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WX78.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BITTERSWEETBERRIES = ""

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BITTERSWEETBERRIES = ""



STRINGS.CHARACTERS.GENERIC.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

--STRINGS.CHARACTERS.WILSON.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WENDY.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WX78.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BITTERSWEETBERRIES_COOKED = ""


STRINGS.CHARACTERS.GENERIC.DESCRIBE.REINGOAT = "They look a bit tipsy."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.REINGOAT = "I wonder what causes the red nose?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.REINGOAT = "You'd better cut down on drinking."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.REINGOAT = "There is no such thing like too much vodka for Wolfgang. You, though..."

STRINGS.CHARACTERS.WENDY.DESCRIBE.REINGOAT = "A pitiful attempt at HO. HO. HO."

STRINGS.CHARACTERS.WX78.DESCRIBE.REINGOAT = "DO YOU KNOW THE KISS OF ELECTRICITY LIKE YOUR DESERT BRETHREN?"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.REINGOAT = "That's not quite a reindeer, but will do for now."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.REINGOAT = "Evidently a local population of Rangifer tarandus - on the inebriated side to add."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.REINGOAT = "I crave a steady haunch of wintery venison!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.REINGOAT = "You look like Santa's mounts!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.REINGOAT = "This is amusing... for a plebeian."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.LEIF_SNOW = "A peculiar blend of the festive and the deadly."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.LEIF_SNOW = "But this doesn't mean Aunt Debbie is coming for Christmas, does it?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.LEIF_SNOW = "Still cheerier than Christmas at the orphanage."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LEIF_SNOW = "Christmas tree walking?!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.LEIF_SNOW = "Its attempts at festivity in this place are so dreadfully inappropriate."

STRINGS.CHARACTERS.WX78.DESCRIBE.LEIF_SNOW = "HOW OFTEN DO YOU NEED TO PLUG YOURSELF IN FOR A RECHARGE?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LEIF_SNOW = "The tradition started in Germany, but how you, poor thing, ended here, evades me."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.LEIF_SNOW = "...I don't think I will be able to chop that one easily. Too cute."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LEIF_SNOW = "Less festivity, more battling!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.LEIF_SNOW = "Santa? We've been good all year, promise!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LEIF_SNOW = "What trickery is that?! This looks like Jack's Christmas tree decorating \"skills\"!"


STRINGS.CHARACTERS.GENERIC.DESCRIBE.RABBIT_SNOW = "Rabbits prepare for winter too."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.RABBIT_SNOW = "It clearly changes its fur for winter!"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.RABBIT_SNOW = "You're white like a dove now. I still want to eat you."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.RABBIT_SNOW = "White! Cuddly! TASTY!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.RABBIT_SNOW = "Just try coaxing me into following you into your hole and beyond, furry fiend."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.RABBIT_SNOW = "How ADORKABLE!"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.RABBIT_SNOW = "A small but tasty coward."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.RABBIT_SNOW = "They would change coat for winter back home as well."

STRINGS.CHARACTERS.WX78.DESCRIBE.RABBIT_SNOW = "CLOSE TO THE HUE OF LIQUID MERCURY. STILL A MEATBAG THOUGH."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RABBIT_SNOW = "Their coat changes with the season to better blend in with the surroundings."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.RABBIT_SNOW = "I swear the earmuffs I will make of you will be more dapper than the first pair."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PERMA_WALRUS_CAMP = "I have a bad feeling about this."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.PERMA_WALRUS_CAMP = "This looks more permanent. Should I prepare for an expeditious retreat?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PERMA_WALRUS_CAMP = "I will fight you with FIRE."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PERMA_WALRUS_CAMP = "Scary monster dwelling."

STRINGS.CHARACTERS.WENDY.DESCRIBE.PERMA_WALRUS_CAMP = "Back to stalk me until the end."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PERMA_WALRUS_CAMP = "I wish I still had that treatise on fortifications..."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PERMA_WALRUS_CAMP = "This looks like trouble to me."

STRINGS.CHARACTERS.WX78.DESCRIBE.PERMA_WALRUS_CAMP = "FOR MEATBAGS, I ADMIRE THEIR LUST FOR HUMANITY DESTRUCTION."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PERMA_WALRUS_CAMP = "We should hide from them. So many meanies..."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PERMA_WALRUS_CAMP = "Thor, give me your might for the impending slaughter!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PERMA_WALRUS_CAMP = "I guess an expeditious retreat from this place would be smart."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.POND_OPEN = "I should seize the opportunity before it freezes over."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.POND_OPEN = "Since it still hasn't frozen over, I could revise my bathyscaphe project."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.POND_OPEN = "Do I need a fishing permit like in Girl Scouts?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.POND_OPEN = "Fishy fish all year long for Wolfgang!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.POND_OPEN = "Ophelia, how's the water?"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.POND_OPEN = "No skating for us."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.POND_OPEN = "Guess I could fish some more in here."

STRINGS.CHARACTERS.WX78.DESCRIBE.POND_OPEN = "DANGEROUS MOISTURE LEVEL. STILL."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POND_OPEN = "H2O achieves its maximum density at about 4°C. I should seize this opportunity."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.POND_OPEN = "Jörmungandr, up for a battle?"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.POND_OPEN = "I'm too delicate to bathe in THIS."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGMAN_BLUE = "A surprisingly cool pigman."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.PIGMAN_BLUE = "A new guinea pig for my experiments?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGMAN_BLUE = "Sorry, it wouldn't work out. You're cool, I'm hot. A clash of priorities."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGMAN_BLUE = "Blue, but still made of bacon."

STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGMAN_BLUE = "Are you feeling blue, you pig?"

STRINGS.CHARACTERS.WX78.DESCRIBE.PIGMAN_BLUE = "CHILLED, BUT SUPRISINGLY COLD-RESILIENT FOR A MEATBAG."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGMAN_BLUE = "Chill out, you bully! Bullying isn't cool!"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGMAN_BLUE = "They look somewhat cold."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGMAN_BLUE = "Its cold stare sends my blood boiling! Let the battle begin!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGMAN_BLUE = "A previously undiscovered species of even-toed ungulates adapted to the subpolar climate of this land."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGMAN_BLUE = "If you aimed for cool, Charlie, this needs more work."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGMAN_GRAY = "They don't look too benevolent."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.PIGMAN_GRAY = "I've never seen your kind before. Care to play my guinea pig?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGMAN_GRAY = "Ashen grey. I guess you might not be that bad."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGMAN_GRAY = "Not pink, but still tasty."

STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGMAN_GRAY = "One creature of a hue befitting this bleak world."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGMAN_GRAY = "Have you seen a ghost to look like that, piggie?"

STRINGS.CHARACTERS.WX78.DESCRIBE.PIGMAN_GRAY = "SILVERY GREY, BUT STILL NOT MADE OF METAL."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGMAN_GRAY = "You grey bully, you."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGMAN_GRAY = "A new foe to be slain? I hope you will be a worthy opponent."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGMAN_GRAY = "For the love of everything that's worthy and literary, I hope there are less than fifty of you grey ones."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGMAN_GRAY = "A slobbering fool, slightly more dapper thanks to all this grey."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGKING_GRAY = "His Plumpness seems to have netted himself a rival."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.PIGKING_GRAY = "As much as I hate it myself, exercise outdoors could help you."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGKING_GRAY = "You're completely ashen. Do you want an ambassador?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGKING_GRAY = "All fat, no muscles. Wolfgang disapproves."

STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGKING_GRAY = "The king of the grey."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGKING_GRAY = "At least you aren't a bully. Still, we should be careful."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGKING_GRAY = "Whoa, you're BIG. Ever heard of Paul Bunyan?"

STRINGS.CHARACTERS.WX78.DESCRIBE.PIGKING_GRAY = "AS STAGNANT AS ANY PUNY MEATBAG."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGKING_GRAY = "They clearly support a patriarchal society. Some reap the benefits."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGKING_GRAY = "Why won't you stand up and face me?!"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGKING_GRAY = "Someone has to be on the top. Heh."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGKING_BLUE = "Cold never bothered him anyway."

--STRINGS.CHARACTERS.WILSON.DESCRIBE.PIGKING_BLUE = "How... festive."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGKING_BLUE = "More Christmasy feels? I feel like parting with my meal, ugh..."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGKING_BLUE = "Has Christmas gear, but no muscles, bah."

STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGKING_BLUE = "He ate too much Christmas pudding."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGKING_BLUE = "Some choppin' could do you good, buddy."

STRINGS.CHARACTERS.WX78.DESCRIBE.PIGKING_BLUE = "A CARBON-BASED MASS OF FLESH. WITH CHRISTMAS LIGHTS. WONDERS NEVER CEASE."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGKING_BLUE = "...Hogfather?"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGKING_BLUE = "I will not fight you this time, if just for the celebrations' sake."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGKING_BLUE = "Will you give us presents?"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGKING_BLUE = "Transient's spin on Santa Claus, heh."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.PERMA_GRASSGEKKO = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASSGEKKO

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MIMI = "Mimi?"
