AddLevelFixed(LEVELTYPE.SURVIVAL, {
	id = "GRAYPRESET",
	name="Grayland",
	desc="Everything gray",
	location = "forest_gray",
	version = 2,
	overrides={
		task_set = "gray",
		krampus = "often",
		flower_cave = "often",
		fern = "often",
		lichen = "often",
	},
	numrandom_set_pieces = 5,
	random_set_pieces = {
		"Chessy_1",
		"Chessy_2",
		"Chessy_3",
		"Chessy_4",
		"Chessy_5",
		"Chessy_6",
		"ChessSpot1",
		"ChessSpot2",
		"ChessSpot3",
		"Maxwell1",
		"Maxwell2",
		"Maxwell3",
		"Maxwell4",
		"Maxwell5",
		"Maxwell6",
		"Maxwell7",
		"Warzone_1",
		"Warzone_2",
		"Warzone_3",
	},
})