AddLevelFixed(LEVELTYPE.SURVIVAL, {
	id = "SLIMEYPRESET",
	name="Slimey",
	desc="Slimey",
	location = "forest_slimey",
	version = 2,
	overrides={
		task_set = "slimey",
		ponds = "often",
		fireflies = "often",
		reeds = "often",
		weather = "often",
		lureplants = "often",
	},
	numrandom_set_pieces = 5,
	random_set_pieces = {
		"Chessy_1",
		"Chessy_2",
		"Chessy_3",
		"Chessy_4",
		"Chessy_5",
		"Chessy_6",
		"ChessSpot1",
		"ChessSpot2",
		"ChessSpot3",
		"Maxwell1",
		"Maxwell2",
		"Maxwell3",
		"Maxwell4",
		"Maxwell5",
		"Maxwell6",
		"Maxwell7",
		"Warzone_1",
		"Warzone_2",
		"Warzone_3",
	},
})
