STRINGS.WILDBEAVER_TALK_FIGHT = {
	"DAM YOU!",
	"GO AWAY!",
	"I FIGHT BACK!",
}
STRINGS.WILDBEAVER_TALK_FOLLOW = {
	"YOU UNDERSTAND ME",
	"LETS BUILD A DAM",
	--"LETS BUILD A WALL",
	"WE NEED MORE WOOD",
}
STRINGS.WILDBEAVER_TALK_GOHOME = {
	"ILL FINISH THE DAM TOMORROW",
	"TIME TO SLEEP",
	"CYA",
}